### ISSUE TITLE
undefined method add_user_to_group

### ISSUE THREAD

**Issue by manderson26** [chef/knife-opc#28]
Chef 12.1.1, knife-opc 0.3.0

I'm seeing knife opc fail to load knife-opc/lib/chef/org.rb, which then fails with 'undefined method add_user_to_group' . There's something odd going on here, since if I understand the cause correctly I can't understand how this hasn't been seen elsewhere. 

I can repro this on a dev-vm; (ubuntu 10.04)

Install chef 12.1.1. (I used curl -L https://www.chef.io/chef/install.sh | sudo bash)
/opt/chef/embedded/bin/gem install knife-opc

% /opt/chef/bin/knife opc -c knife-pivotal.rb  org user add ponyville rainbowdash --admin  -VV
...
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/knife-opc-0.3.0/lib/chef/knife/opc_org_user_add.rb:56:in `run': undefined method `add_user_to_group' for #<Chef::Org:0x0000000381c178> (NoMethodError)
	from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
	from /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
	from /opt/chef/embedded/apps/chef/lib/chef/knife.rb:214:in `run'
	from /opt/chef/embedded/apps/chef/lib/chef/application/knife.rb:138:in `run'
	from /opt/chef/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:52:in `load'
	from /usr/bin/knife:52:in `<main>'

If I insert on line 52 
pp :class=>org.class, :methods=>org.methods.sort-Object.methods, :loc=>org.method(:associate_user).source_location

I get:
{:class=>Chef::Org,
 :methods=>
  [:associate_user,
   :chef_rest,
   :create,
   :destroy,
   :dissociate_user,
   :full_name,
   :guid,
   :lazy,
   :private_key,
   :save,
   :set_or_return,
   :to_hash,
   :update,
   :validate],
 :loc=>["/opt/chef/embedded/apps/chef/lib/chef/org.rb", 103]}

None of the methods I'd expect to be there are present, and
associate_user is coming from chef; to be precise it looks like the code is picking up
https://github.com/chef/chef/blob/master/lib/chef/org.rb#L103
instead of
https://github.com/chef/knife-opc/blob/master/lib/chef/org.rb#L85
and only the knife-opc org definition has add_user_to_group_defined.

What I think is happening is that the require at
https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_org_user_add.rb#L31
is seeing that knife has already loaded chef/org.rb from chef/lib/chef/org.rb
and not loading the knife-opc/lib/chef/org.rb

And renaming org.rb to org_override.rb and adding require 'chef/org_override.rb' to opc_org_user_add.rb#L31  makes things work again.  

I suspect other instances of 'require 'chef/org'" will need the same treatment, but there's probably a cleaner way to fix this up than my hack.

**Comment by stevendanna** [comment]
@manderson26 Interesting, it is possible this has been broken since we updated to chef 12 internally (which includes a Chef::Org class that was mostly copy-pasta from this gem but with that function removed).  Thanks for tracking this down, I'll fix it up today.

We've seen issues in the past where issues re gem loading are sensitive to glob ordering on the filesystem which might be why we didn't see this before.
