### ISSUE TITLE
--enable-external-auth command broken

### ISSUE THREAD

**Issue by misheska** [chef/knife-opc#30]
Filing here, just in case the change in option from `--enable_external_auth` to `--enable-external-auth` is considered a regression.

If you try to run `chef-server-ctl password` with the `--enable-external-auth` command, it doesn't work. You get the following error:

    Error: invalid option: --enable_external_auth

After digging into the code that does the handoff to the knife_opc module:
https://github.com/chef/opscode-omnibus/blob/master/files/private-chef-ctl-commands/password.rb#L53

It looks like the code hardcodes the option to `--enable_external_auth`, which appears to no longer exists in the knife opc module (it's now `--enable-external-auth`. Also it prevents using the short option -e as a workaround.

Here's where the option has changed to `--enable-external-auth`:

https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_user_password.rb#L25

**Comment by stevendanna** [comment]
@misheska I agree that it is potentially a regression, but --enable-external-auth is definitely what we want into the future, so I'm going to close this and fix it in opscode-omnibus:

https://github.com/chef/opscode-omnibus/pull/747
