### ISSUE TITLE
knife cookbook site install requires single repo

### ISSUE THREAD

**Issue by phillipbroberts** [chef/knife-opc#38]
knife cookbook site install <cookbook> favors the single git repository method of managing cookbooks over the preferred 1 repo per cookbook method. 

knife should support the preferred 1 repo per cookbook method. 

Ex: 

$ knife cookbook site install sudo
Installing sudo to C:/foo/chef-repo/cookbooks
ERROR: The cookbook repo C:/foo/chef-repo/cookbooks is not a git repository.
Use `git init` to initialize a git repo

**Comment by stevendanna** [comment]
Hi! Thanks for the bug report, but I think this related to `knife cookbook site install` which is a core knife command.  Would you mind reopening this report against the chef repository?:

https://github.com/chef/chef
