### ISSUE TITLE
`knife osc user list` and `knife opc user list` give different results

### ISSUE THREAD

**Issue by patcon** [chef/knife-opc#41]
# Version:

```
~/scratch/learn-chef-tutorial (master ✘)✹✭ ᐅ chef --version
Chef Development Kit Version: 1.3.13
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 5.6.2
kitchen version: 1.15.0
~/scratch/learn-chef-tutorial (master ✘)✹✭ ᐅ chef gem list | grep opc
knife-opc (0.3.2)
```

# Environment:

Followed chef-automate tutorial and arrived at final step, which recommended testing `chef-opc`:
https://learn.chef.io/tutorials/manage-a-node/ubuntu/automate/run-chef-client-periodically/#step4

# Scenario:

I'm using the `delivery` user credentials on my workstation as the tutorial leads me to do, and am getting different results from knife command for open-source and command for private chef:

```
~/scratch/learn-chef-tutorial (master ✘)✹✭ ᐅ knife osc user list
delivery
~/scratch/learn-chef-tutorial (master ✘)✹✭ ᐅ knife opc user list
ERROR: You authenticated successfully to https://chef.example.com/organizations/automate as delivery but you are not authorized for this action
Response:  missing read permission
```

# Steps to Reproduce:

Tutorial on digitalocean servers. See above.

# Expected Result:

Would expect the open source chef-server command (`knife osc <blah>`) to match the results of the private chef-server command (`knife opc <blah>`).

Any advice is appreciated!

cc: @mrjcleaver

**Comment by santosgian28** [comment]
Is it possible to use a different admin or grant a user aside from Pivotal?

**Comment by snehaldwivedi** [comment]
@patcon I have tested `knife osc user list` on `Chef Infra Client version: 16.2.73`  commands related to `knife osc`  was removed https://github.com/chef/chef/pull/7868 so currently does on exists.  `knife opc user list` Is working fine but will be removed once merged with https://github.com/chef/chef/pull/10187 in result we can use `knife user list` to get all user list. I will suggest you to please use the latest versions with `knife opc` commands.

Please let us know if you have any  queries.

**Comment by patcon** [comment]
Ok, I'm not using the project right now, but really appreciate the way you're going through old issues and checking in :) sounds like I should close this one, but pls do re-open if I'm misunderstanding...!
